/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: simplelib.i

#ifndef SWIG_simplelib_WRAP_H_
#define SWIG_simplelib_WRAP_H_

class Swig_memory;

class SwigDirector_SimpleClassCallback : public SimpleClassCallback
{
 public:
  SwigDirector_SimpleClassCallback(int swig_p);
  virtual ~SwigDirector_SimpleClassCallback();
  void _swig_upcall_onStart() {
    SimpleClassCallback::onStart();
  }
  virtual void onStart();
 private:
  intgo go_val;
  Swig_memory *swig_mem;
};

#endif
